
//
//  swipe.m
//  Generated by FoneMonkey - http://www.gorillalogic.com/FoneMonkey
//  Need help? Gorilla Logic provides complete FoneMonkey consulting services!
//
//  See Also: http://developer.apple.com/iphone/library/documentation/Xcode/Conceptual/iphone_development/135-Unit_Testing_Applications/unit_testing_applications.html

#import <SenTestingKit/SenTestingKit.h>
#import <UIKit/UIKit.h>
#import "FoneMonkeyAPI.h"

@interface swipe : SenTestCase {
}
- (void) testSomething;    
@end

@implementation swipe
- (void) testSomething {
//	NSString* lastResult = [FoneMonkeyAPI playFile:@"swipe"];

	NSMutableArray* array = [NSMutableArray array];
	[array addObject:[FMCommandEvent command:@"Touch" className:@"UITextField" monkeyID:@"#0" delay:@"500" timeout:@"100" args:[NSArray arrayWithObjects:@"52", @"17", nil]]];
	[array addObject:[FMCommandEvent command:@"InputText" className:@"UITextField" monkeyID:@"#0" delay:@"71.797" timeout:@"100" args:[NSArray arrayWithObjects:@"adam", nil]]];
	[array addObject:[FMCommandEvent command:@"Touch" className:@"UIRoundedRectButton" monkeyID:@"Add" delay:@"811.478" timeout:@"100" args:[NSArray arrayWithObjects:@"22", @"25", nil]]];
	[array addObject:[FMCommandEvent command:@"swipe" className:@"SwipableView" monkeyID:@"#0" delay:@"1473.47" timeout:@"100" args:[NSArray arrayWithObjects:@"28.000000", @"20.000000", nil]]];

	NSString* lastResult = [FoneMonkeyAPI playCommands:array];
	STAssertNil(lastResult, lastResult);  	
}
@end
